services:
  # Database Service
  db:
    image: postgres:${DB_VERSION}
    ports:
      - ${DB_PORT}:5432
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - volume:/var/lib/postgresql/data
    networks:
      - network

volumes:
  volume:

networks:
  network:
